site_name: Lambdaflow
site_description: "Secure C# polyglot framework—any backend, modern WebView UI"
theme:
  name: material
  language: en
nav:
  - Home: index.md

  - Usage Guide:
    - Introducion: usage/index.md

  - Technical Reference: 
    - Introducion: tech/index.md
    - Build:
      - Overview: tech/build/index.md
      - Build mode:
      - Run mode:
    - Packaging:
      - Overview: tech/packaging/index.md
    - Runtime:
      - Overview: tech/runtime/index.md

plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        es: Español
      nav_translations:
        es:
          Home: Inicio

          "Usage Guide": "Guía de uso"
          Introducion: "Introducción"
          "Technical Reference": "Referencia técnica"
          Build: "Compilación"
          Overview: "Descripción general"
          "Build mode": "Modo Build"
          "Run mode": "Modo Run"
          Packaging: "Empaquetado"
          Runtime: "Tiempo de ejecución"
