site_name: Lambdaflow
site_description: "Secure C# polyglot framework—any backend, modern WebView UI"
theme:
  name: material
  language: en
nav:
  - Home: index.md

  - Usage Guide:
    - Introduction: usage/index.md

  - Technical Reference: 
    - Introduction: tech/index.md
    - Build:
      - Overview: tech/build/index.md
    - Packaging:
      - Overview: tech/packaging/index.md
    - Runtime:
      - Overview: tech/runtime/index.md

plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
      nav_translations:
        es:
          Home: Inicio

          "Usage Guide": "Guía de uso"
          Introduction: "Introducción"
          "Technical Reference": "Referencia técnica"
          Build: "Compilación"
          Overview: "Descripción general"
          Packaging: "Empaquetado"
          Runtime: "Tiempo de ejecución"
